version: '3.7'

services:
  web:
    image: ${SWARMLET_REGISTRY}/${APP_NAME}
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.services.${APP_NAME}.loadbalancer.server.port=${APP_PORT}
        - traefik.http.routers.${APP_NAME}.rule=Host(`${APP_NAME}.${ROOT_DOMAIN}`)
        - traefik.http.routers.${APP_NAME}.entrypoints=http,https
        - traefik.http.routers.${APP_NAME}.middlewares=redirect@file
    networks:
      - python-docker
      - traefik-public

  redis:
    image: redis:alpine
    networks:
      - swarmlet-network

networks:
  swarmlet-network:
    external: true
  traefik-public:
    external: true
