version: '3.7'

services:
  web:
    image: sentry:latest
    environment:
      SENTRY_REDIS_HOST: redis
      SENTRY_SECRET_KEY: ${SENTRY_SECRET_KEY}
      SENTRY_POSTGRES_HOST: db
      SENTRY_POSTGRES_PORT: 5432
      SENTRY_DB_NAME: postgres
      SENTRY_DB_USER: postgres
      SENTRY_DB_PASSWORD: postgres
    networks:
      - sentry-network
      - traefik-public
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.services.${APP_NAME}.loadbalancer.server.port=${APP_PORT}
        - traefik.http.routers.${APP_NAME}.rule=Host(`${APP_NAME}.${ROOT_DOMAIN}`)
        - traefik.http.routers.${APP_NAME}.entrypoints=https
        - traefik.http.routers.${APP_NAME}.middlewares=redirect@file

  redis:
      image: redis:alpine
      networks:
        - sentry-network

  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - sentry-network

networks:
  sentry-network:
  traefik-public:
    external: true
