version: '3.7'

# Built-in environment variables
# SWARMLET_REGISTRY // Defaults to the internal swarm registry at localhost:5000/v2

services:
  basic-example:
    image: ${SWARMLET_REGISTRY}/${APP_NAME}
    build: .

  web:
    image: hashicorp/http-echo
    command: ['-text', 'Hello ${APP_NAME}..']
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.services.${APP_NAME}.loadbalancer.server.port=${APP_PORT}
        - traefik.http.routers.${APP_NAME}.rule=Host(`${APP_NAME}.${ROOT_DOMAIN}`)
        - traefik.http.routers.${APP_NAME}.entrypoints=http,https
        - traefik.http.routers.${APP_NAME}.middlewares=redirect@file
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
