version: '3.4'

services:
  verdaccio:
    image: verdaccio/verdaccio:${VERDACCIO_VERSION}
    networks:
      - traefik-public
      - swarmlet-network
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.services.${APP_NAME}.loadbalancer.server.port=${APP_PORT}
        - traefik.http.routers.${APP_NAME}.rule=Host(`${APP_NAME}.${ROOT_DOMAIN}`)
        - traefik.http.routers.${APP_NAME}.entrypoints=https
        - traefik.http.routers.${APP_NAME}.middlewares=redirect@file
    volumes:
      - ./config.yaml:/verdaccio/conf/config.yaml
      - ./htpasswd:/verdaccio/conf/htpasswd
      - ${VERDACCIO_DATA}:/verdaccio/storage

networks:
  web:
    external: true
  swarmlet-network:
    external: true
  traefik-public:
    external: true
